name: Reduce README
on:
  push:
    paths:
      - src/main/asciidoc/README.adoc
    branches: [ '**' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.REDUCE_README_TOKEN }}
      - name: Install Asciidoctor Reducer
        run: sudo gem install asciidoctor-reducer
      - name: Reduce README
        # to preserve preprocessor conditionals, add the --preserve-conditionals option
        run: asciidoctor-reducer -o README.adoc src/main/asciidoc/README.adoc
      - name: Commit and Push README
        uses: EndBug/add-and-commit@v9
        with:
          add: README.adoc
          message: Rebuild reduced README
          committer_name: GitHub Actions
          committer_email: actions@github.com